### ISSUE TITLE
containerd.sock mapping

### ISSUE THREAD

**Issue by ugurarpaci** [alertlogic/al-agent-container#32]
Hello,

When we use containerd as a container runtime engine on the hosts, is it safe to map containerd.sock (since docker.sock is missing)? I wonder if the agent implementation is compatible with pure containerd integration?

**Comment by akontsevoy** [comment]
At the moment, pure containerd (protobuf interface) integration is not supported; it is a feature request we are considering. The agent can still be run in a containerd environment with host network mode, and it will capture host interface traffic and listen for syslogs where enabled; but it will not discover and declare other containers running on the host, nor capture traffic from their virtual network interfaces, nor collect their native (stdout/stderr) logs as it would with docker runtime (HTTP interface) integration.
Thus, for the moment there is no use in exposing containerd.sock to AL agent container.

**Comment by Malet** [comment]
Since [kubernetes has now deprecated the docker runtime](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/), can we expect support for common CRIs (GKE is using containerd) in the near future?
