### ISSUE TITLE
ECR Public Gallery out of sync with Docker Hub images

### ISSUE THREAD

**Issue by nakulpathak3** [alertlogic/al-agent-container#37]
Hey all, to avoid the DockerHub Rate Limits, we have been using the ECR public gallery for pulling the `al-agent-container`. However, it looks like the [ECR gallery hasn't been updated in 6 months](https://gallery.ecr.aws/alertlogic/al-agent-container) while there have been [multiple updates to DockerHub](https://hub.docker.com/r/alertlogic/al-agent-container/tags). 

I was wondering if there is a broken flow somewhere that does not keep the two in-sync and if it could be fixed so we get the latest version of the image in our builds while using ECR.

**Comment by motobob** [comment]
@akontsevoy ^

**Comment by akontsevoy** [comment]
This has been resolved with `v2.24.0-1958` release; from now on this ECR repository will be kept up to date with respect to Docker Hub.
