### ISSUE TITLE
multi-architecture image

### ISSUE THREAD

**Issue by dschaaff** [alertlogic/al-agent-container#38]
The alert logic agent and container should support arm64 instances allowing customer to utilize AWS graviton instance types.

**Comment by yoz2326** [comment]
We also need this, it's the only container we can't run on ARM instances on our Kubernetes estate

**Comment by akontsevoy** [comment]
This has been published starting with image version `v2.23.0-1933` (which, along with the `latest` tag, is an amd64+arm64 multi-arch build from now on).
